apiVersion: v1
kind: Service
metadata:
  name: nginx-argocd-01
  labels:
    app: nginx01
spec:
  selector:
    app: nginx01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
