apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx02

  template:
    metadata:
      labels:
        app: nginx02
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80